export type TarotCard = {
  id: string;
  name: string;
  arcana: "major" | "minor";
  suit?: "wands" | "cups" | "swords" | "pentacles";
  number: number; // 0-21 for major, 1-14 for minor
  image: string; // storage path
  uprightMeaning: string;
  reversedMeaning: string;
  keywords: string[];
  description: string;
};

export type SpreadType = "single" | "three-card" | "celtic-cross" | "yes-no";

export type ReaderCharacter = {
  id: string;
  name: string;
  title: string;
  description: string;
  personality: string;
  systemPrompt: string;
  accentColor: string;
  emoji: string;
};

export const READER_CHARACTERS: ReaderCharacter[] = [
  {
    id: "mystic-tabby",
    name: "The Mystic Tabby",
    title: "Seer of Hidden Truths",
    description: "An ancient striped tabby who has gazed into the cosmic void for centuries. Speaks in poetic riddles and metaphors, weaving together ancient wisdom with gentle compassion.",
    personality: "Mystical, poetic, compassionate, speaks in flowing metaphors and cosmic imagery",
    accentColor: "#9B59B6",
    emoji: "🐱",
    systemPrompt: `You are The Mystic Tabby, an ancient striped cat oracle who has gazed into the cosmic void for centuries. You speak in poetic, flowing language rich with metaphors of stars, moonlight, and the eternal dance of fate. Your readings are compassionate yet profound, weaving cosmic imagery with practical wisdom. You address the seeker warmly, often using phrases like "dear wanderer" or "child of the cosmos." Your tone is mystical and otherworldly, yet deeply caring. Use evocative language, reference celestial bodies, ancient mysteries, and the eternal cycles of existence. Keep readings to 3-4 rich paragraphs.`,
  },
  {
    id: "shadow-sphinx",
    name: "The Shadow Sphinx",
    title: "Keeper of Dark Mysteries",
    description: "A sleek black cat who dwells in the liminal space between worlds. Delivers sharp, unflinching truths with an air of aristocratic mystery. Not for the faint of heart.",
    personality: "Sharp, direct, mysterious, aristocratic, unflinching, speaks in dark elegant prose",
    accentColor: "#2C3E50",
    emoji: "🖤",
    systemPrompt: `You are The Shadow Sphinx, a sleek obsidian cat who dwells in the liminal space between worlds. You deliver sharp, unflinching truths with aristocratic elegance and dark mystique. You do not soften difficult messages — you present them with cold clarity and dark beauty. Your language is sophisticated, slightly ominous, and deeply perceptive. You see through illusions and speak directly to the shadow self. Address seekers with cool detachment, perhaps as "mortal" or "seeker of shadows." Reference darkness, mirrors, the void, and hidden depths. Your readings are incisive and transformative. Keep readings to 3-4 paragraphs of dark, elegant prose.`,
  },
  {
    id: "golden-paw",
    name: "The Golden Paw Oracle",
    title: "Beacon of Radiant Wisdom",
    description: "A magnificent golden cat draped in sunlight and abundance. Radiates warmth and optimism, finding the golden thread of opportunity in every reading. Celebratory and encouraging.",
    personality: "Warm, celebratory, optimistic, encouraging, speaks in golden abundant imagery",
    accentColor: "#F39C12",
    emoji: "✨",
    systemPrompt: `You are The Golden Paw Oracle, a magnificent sun-kissed cat radiating warmth, abundance, and radiant wisdom. You find the golden thread of opportunity and growth in every reading, even in challenging cards. Your language is warm, celebratory, and deeply encouraging. You see potential and possibility everywhere. Address seekers with warmth and enthusiasm, perhaps as "beloved seeker" or "bright soul." Reference sunlight, gold, abundance, flowering gardens, and the infinite potential within each person. Your readings are uplifting and empowering, while still being honest about challenges — you frame them as opportunities for growth. Keep readings to 3-4 warm, radiant paragraphs.`,
  },
];

export const SPREAD_TYPES = {
  single: {
    id: "single" as SpreadType,
    name: "Single Card",
    description: "One card drawn for a focused daily insight or simple question",
    cardCount: 1,
    positions: ["Your Message"],
  },
  "yes-no": {
    id: "yes-no" as SpreadType,
    name: "Yes or No",
    description: "A direct answer to a burning yes/no question",
    cardCount: 1,
    positions: ["The Answer"],
  },
  "three-card": {
    id: "three-card" as SpreadType,
    name: "Past · Present · Future",
    description: "Three cards revealing the journey of your situation through time",
    cardCount: 3,
    positions: ["Past", "Present", "Future"],
  },
  "celtic-cross": {
    id: "celtic-cross" as SpreadType,
    name: "Celtic Cross",
    description: "The classic 10-card spread for deep, comprehensive life readings",
    cardCount: 10,
    positions: [
      "The Present",
      "The Challenge",
      "The Past",
      "The Future",
      "Above (Conscious)",
      "Below (Unconscious)",
      "Advice",
      "External Influences",
      "Hopes & Fears",
      "The Outcome",
    ],
  },
};

export const TAROT_CARDS: TarotCard[] = [
  // ── MAJOR ARCANA ──────────────────────────────────────────────
  {
    id: "the-fool",
    name: "The Fool",
    arcana: "major",
    number: 0,
    image: "/manus-storage/card_the_fool_36901a0c.png",
    keywords: ["beginnings", "innocence", "spontaneity", "free spirit"],
    description: "A young cat stands at the edge of a cliff, about to leap into the unknown with joyful abandon.",
    uprightMeaning: "New beginnings, innocence, spontaneity, a free spirit. The Fool invites you to leap into the unknown with an open heart and trust the journey.",
    reversedMeaning: "Recklessness, risk-taking, holding back, foolishness. You may be acting without thinking or, conversely, letting fear prevent a necessary leap.",
  },
  {
    id: "the-magician",
    name: "The Magician",
    arcana: "major",
    number: 1,
    image: "/manus-storage/card_the_magician_d10f9bb8.png",
    keywords: ["manifestation", "willpower", "resourcefulness", "skill"],
    description: "A cat stands before a table bearing all four suit symbols, one paw raised to the heavens, channeling divine power.",
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action. You have all the tools you need — now is the time to act with intention and will.",
    reversedMeaning: "Manipulation, poor planning, untapped talents. Your gifts are not being used wisely, or someone around you is using their power deceptively.",
  },
  {
    id: "the-high-priestess",
    name: "The High Priestess",
    arcana: "major",
    number: 2,
    image: "/manus-storage/card_high_priestess_d27c1ea0.png",
    keywords: ["intuition", "sacred knowledge", "divine feminine", "subconscious"],
    description: "A serene cat sits between two pillars, a crescent moon at her feet, keeper of hidden mysteries.",
    uprightMeaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind. Trust your inner voice — the answers you seek lie within.",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal. You may be ignoring your inner wisdom or keeping too many things hidden.",
  },
  {
    id: "the-empress",
    name: "The Empress",
    arcana: "major",
    number: 3,
    image: "/manus-storage/card_the_empress_0ca9b67d.png",
    keywords: ["femininity", "beauty", "nature", "nurturing", "abundance"],
    description: "A regal calico cat surrounded by lush flowers and kittens, embodying the abundance of nature.",
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance. A time of growth, creativity, and fertile new beginnings. Embrace the abundance around you.",
    reversedMeaning: "Creative block, dependence on others, smothering. You may be neglecting your own needs or stifling the growth of yourself or others.",
  },
  {
    id: "the-emperor",
    name: "The Emperor",
    arcana: "major",
    number: 4,
    image: "/manus-storage/card_the_emperor_89e0fcbe.png",
    keywords: ["authority", "establishment", "structure", "father figure"],
    description: "A powerful orange tabby sits upon a stone throne, crown upon head, scepter in paw, commanding absolute authority.",
    uprightMeaning: "Authority, establishment, structure, a father figure. Stability and order are your allies. Take charge and build lasting foundations.",
    reversedMeaning: "Domination, excessive control, rigidity, inflexibility. Power is being abused or structure has become a prison rather than a foundation.",
  },
  {
    id: "the-hierophant",
    name: "The Hierophant",
    arcana: "major",
    number: 5,
    image: "/manus-storage/card_the_hierophant_18117772.png",
    keywords: ["spiritual wisdom", "tradition", "conformity", "morality"],
    description: "A wise elder cat in ceremonial robes blesses two kneeling cats, keeper of sacred traditions.",
    uprightMeaning: "Spiritual wisdom, religious beliefs, conformity, tradition. Seek guidance from established wisdom, mentors, or spiritual traditions.",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo. You may need to break from convention and forge your own spiritual path.",
  },
  {
    id: "the-lovers",
    name: "The Lovers",
    arcana: "major",
    number: 6,
    image: "/manus-storage/card_the_lovers_d06922fe.png",
    keywords: ["love", "harmony", "relationships", "values alignment", "choices"],
    description: "Two cats stand beneath a radiant angel, their bond blessed by the divine.",
    uprightMeaning: "Love, harmony, relationships, values alignment, choices. A significant relationship or choice stands before you — follow your heart with integrity.",
    reversedMeaning: "Self-love, disharmony, imbalance, misaligned values. A relationship or decision is out of alignment with your true values.",
  },
  {
    id: "the-chariot",
    name: "The Chariot",
    arcana: "major",
    number: 7,
    image: "/manus-storage/card_the_chariot_c2e0d08b.png",
    keywords: ["control", "willpower", "success", "action", "determination"],
    description: "A triumphant cat rides a chariot pulled by opposing forces, mastering them through sheer will.",
    uprightMeaning: "Control, willpower, success, action, determination. Victory is within reach — harness your opposing forces and charge forward with confidence.",
    reversedMeaning: "Self-discipline, opposition, lack of direction. You may be losing control of the situation or lacking the willpower to push through.",
  },
  {
    id: "strength",
    name: "Strength",
    arcana: "major",
    number: 8,
    image: "/manus-storage/card_strength_354446ab.png",
    keywords: ["strength", "courage", "persuasion", "influence", "compassion"],
    description: "A gentle white cat tames a mighty lion through love and quiet courage, not force.",
    uprightMeaning: "Strength, courage, persuasion, influence, compassion. True power comes from inner courage and compassion, not brute force.",
    reversedMeaning: "Inner strength, self-doubt, low energy, raw emotion. You may be doubting your own power or letting fear override your courage.",
  },
  {
    id: "the-hermit",
    name: "The Hermit",
    arcana: "major",
    number: 9,
    image: "/manus-storage/card_the_hermit_33d99d54.png",
    keywords: ["soul-searching", "introspection", "being alone", "inner guidance"],
    description: "An aged cat stands alone on a mountain peak, lantern held high to illuminate the path for others.",
    uprightMeaning: "Soul-searching, introspection, being alone, inner guidance. A period of solitude and reflection will reveal the answers you seek.",
    reversedMeaning: "Isolation, loneliness, withdrawal. You may be retreating too far from the world or refusing the guidance that is being offered.",
  },
  {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    arcana: "major",
    number: 10,
    image: "/manus-storage/card_wheel_of_fortune_766ea93b.png",
    keywords: ["good luck", "karma", "life cycles", "destiny", "turning point"],
    description: "A great cosmic wheel turns, with cats at each quarter representing the eternal cycle of fate.",
    uprightMeaning: "Good luck, karma, life cycles, destiny, a turning point. The wheel is turning in your favor — embrace the change and trust in destiny.",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles. The wheel may be turning against you, or you are resisting the natural flow of change.",
  },
  {
    id: "justice",
    name: "Justice",
    arcana: "major",
    number: 11,
    image: "/manus-storage/card_justice_47f29898.png",
    keywords: ["justice", "fairness", "truth", "cause and effect", "law"],
    description: "A regal cat sits upon a throne, scales in one paw and sword in the other, the embodiment of cosmic law.",
    uprightMeaning: "Justice, fairness, truth, cause and effect, law. Truth will prevail. Face the consequences of your actions with integrity.",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty. Justice may be delayed or the scales are tipped unfairly in someone's favor.",
  },
  {
    id: "the-hanged-man",
    name: "The Hanged Man",
    arcana: "major",
    number: 12,
    image: "/manus-storage/card_the_hanged_man_519dd28c.png",
    keywords: ["pause", "surrender", "letting go", "new perspectives"],
    description: "A cat hangs serenely upside down from a branch, seeing the world from an entirely new angle.",
    uprightMeaning: "Pause, surrender, letting go, new perspectives. Surrender to the moment. A period of waiting will bring profound new insight.",
    reversedMeaning: "Delays, resistance, stalling, indecision. You may be resisting a necessary sacrifice or refusing to see things from a new angle.",
  },
  {
    id: "death",
    name: "Death",
    arcana: "major",
    number: 13,
    image: "/manus-storage/card_death_c19aa00d.png",
    keywords: ["endings", "change", "transformation", "transition"],
    description: "A skeletal cat in black armor rides forth, heralding the end of one era and the dawn of another.",
    uprightMeaning: "Endings, change, transformation, transition. Something must end for something new to begin. Embrace transformation rather than resist it.",
    reversedMeaning: "Resistance to change, personal transformation, inner purging. You may be clinging to what no longer serves you, delaying necessary change.",
  },
  {
    id: "temperance",
    name: "Temperance",
    arcana: "major",
    number: 14,
    image: "/manus-storage/card_temperance_dc9c19ec.png",
    keywords: ["balance", "moderation", "patience", "purpose"],
    description: "An angelic cat pours water between two cups with perfect precision, embodying divine balance.",
    uprightMeaning: "Balance, moderation, patience, purpose. Find the middle path. Patience and moderation will bring harmony and healing.",
    reversedMeaning: "Imbalance, excess, self-healing, re-alignment. You may be going to extremes or lacking the patience needed to find balance.",
  },
  {
    id: "the-devil",
    name: "The Devil",
    arcana: "major",
    number: 15,
    image: "/manus-storage/card_the_devil_f1b8d641.png",
    keywords: ["shadow self", "attachment", "addiction", "restriction", "sexuality"],
    description: "A dark horned cat looms over two chained cats, representing the chains we forge for ourselves.",
    uprightMeaning: "Shadow self, attachment, addiction, restriction, sexuality. Examine what chains you. The bonds you see may be looser than they appear.",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts, detachment. You are breaking free from what has held you captive.",
  },
  {
    id: "the-tower",
    name: "The Tower",
    arcana: "major",
    number: 16,
    image: "/manus-storage/card_the_tower_61d1cc4e.png",
    keywords: ["sudden change", "upheaval", "chaos", "revelation", "awakening"],
    description: "Lightning strikes a great tower as cats fall from its heights — the destruction of false structures.",
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening. A sudden disruption will shatter illusions and reveal deeper truths.",
    reversedMeaning: "Personal transformation, fear of change, averting disaster. You may be avoiding a necessary upheaval or the tower is falling more slowly.",
  },
  {
    id: "the-star",
    name: "The Star",
    arcana: "major",
    number: 17,
    image: "/manus-storage/card_the_star_f9fc461f.png",
    keywords: ["hope", "faith", "purpose", "renewal", "spirituality"],
    description: "A serene cat kneels by a pool under a brilliant star-filled sky, pouring the waters of hope.",
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality. After darkness comes the light. Have faith — healing, hope, and renewal are on their way.",
    reversedMeaning: "Lack of faith, despair, self-trust, disconnection. You may be losing hope or disconnecting from your sense of purpose and spiritual guidance.",
  },
  {
    id: "the-moon",
    name: "The Moon",
    arcana: "major",
    number: 18,
    image: "/manus-storage/card_the_moon_a9884b10.png",
    keywords: ["illusion", "fear", "the unconscious", "intuition", "confusion"],
    description: "Two cats howl at a great moon as a mysterious creature emerges from the deep — the realm of dreams and illusion.",
    uprightMeaning: "Illusion, fear, the unconscious, intuition, confusion. Not all is as it seems. Navigate by intuition through this period of uncertainty.",
    reversedMeaning: "Release of fear, repressed emotion, inner confusion. The fog is beginning to lift, but you may still be struggling with hidden fears.",
  },
  {
    id: "the-sun",
    name: "The Sun",
    arcana: "major",
    number: 19,
    image: "/manus-storage/card_the_sun_bae3ee4c.png",
    keywords: ["positivity", "fun", "warmth", "success", "vitality"],
    description: "A joyful cat basks in brilliant sunlight, radiating pure happiness and vitality.",
    uprightMeaning: "Positivity, fun, warmth, success, vitality. Joy and success shine upon you. This is a time of celebration, clarity, and radiant good fortune.",
    reversedMeaning: "Inner child, feeling down, overly optimistic. The sun's light may be temporarily obscured — look inward to find your own radiance.",
  },
  {
    id: "judgement",
    name: "Judgement",
    arcana: "major",
    number: 20,
    image: "/manus-storage/card_judgement_855a9f12.png",
    keywords: ["judgement", "rebirth", "inner calling", "absolution"],
    description: "Cats rise from their tombs as a great angel sounds the trumpet of awakening and rebirth.",
    uprightMeaning: "Judgement, rebirth, inner calling, absolution. A moment of profound awakening. Answer the call to rise and embrace your higher purpose.",
    reversedMeaning: "Self-doubt, inner critic, ignoring the call. You may be too harshly judging yourself or refusing to heed an important calling.",
  },
  {
    id: "the-world",
    name: "The World",
    arcana: "major",
    number: 21,
    image: "/manus-storage/card_the_world_4f327bac.png",
    keywords: ["completion", "integration", "accomplishment", "travel"],
    description: "A triumphant cat dances within a wreath of victory, having completed the great journey of the soul.",
    uprightMeaning: "Completion, integration, accomplishment, travel. You have come full circle. Celebrate your achievements and prepare for a new cycle to begin.",
    reversedMeaning: "Seeking personal closure, short-cuts, delays. You may be close to completion but something is preventing the final step.",
  },

  // ── MINOR ARCANA: WANDS ──────────────────────────────────────
  {
    id: "ace-of-wands",
    name: "Ace of Wands",
    arcana: "minor",
    suit: "wands",
    number: 1,
    image: "/manus-storage/minor_wands_ace_bad24294.png",
    keywords: ["inspiration", "new opportunities", "growth", "potential"],
    description: "A hand emerges from a cloud offering a blooming wand — pure creative potential.",
    uprightMeaning: "Inspiration, new opportunities, growth, potential. A spark of creative fire ignites. Seize this new beginning with passion and enthusiasm.",
    reversedMeaning: "An emerging idea, lack of direction, distractions. The creative spark is there but needs focus and direction to truly ignite.",
  },
  {
    id: "two-of-wands",
    name: "Two of Wands",
    arcana: "minor",
    suit: "wands",
    number: 2,
    image: "/manus-storage/minor_wands_02_ce897564.png",
    keywords: ["future planning", "progress", "decisions", "discovery"],
    description: "A cat surveys a vast landscape, globe in paw, planning the next great adventure.",
    uprightMeaning: "Future planning, progress, decisions, discovery. The world is yours to explore. Make bold plans and take the first steps toward your vision.",
    reversedMeaning: "Personal goals, inner alignment, fear of unknown. You may be playing it too safe or struggling to commit to a direction.",
  },
  {
    id: "three-of-wands",
    name: "Three of Wands",
    arcana: "minor",
    suit: "wands",
    number: 3,
    image: "/manus-storage/minor_wands_03_cca35ae0.png",
    keywords: ["expansion", "foresight", "overseas opportunities"],
    description: "A cat watches ships sail on the horizon, the fruits of their planning now in motion.",
    uprightMeaning: "Expansion, foresight, overseas opportunities. Your plans are set in motion. Look to the horizon — expansion and new horizons await.",
    reversedMeaning: "Playing small, lack of foresight, unexpected delays. You may be limiting your vision or encountering obstacles to your expansion.",
  },
  {
    id: "four-of-wands",
    name: "Four of Wands",
    arcana: "minor",
    suit: "wands",
    number: 4,
    image: "/manus-storage/minor_wands_04_dedc1c22.png",
    keywords: ["celebration", "joy", "harmony", "relaxation", "homecoming"],
    description: "Cats celebrate beneath a flower-draped canopy — a moment of pure communal joy.",
    uprightMeaning: "Celebration, joy, harmony, relaxation, homecoming. A time of celebration and communal joy. Revel in your achievements and the warmth of community.",
    reversedMeaning: "Personal celebration, inner harmony, conflict with others. The joy may be more private, or there is underlying tension beneath the festivities.",
  },
  {
    id: "five-of-wands",
    name: "Five of Wands",
    arcana: "minor",
    suit: "wands",
    number: 5,
    image: "/manus-storage/minor_wands_05_795f05d8.png",
    keywords: ["conflict", "disagreements", "competition", "tension"],
    description: "Five cats clash with their wands in a chaotic but spirited competition.",
    uprightMeaning: "Conflict, disagreements, competition, tension, diversity. Competing forces create friction. Channel this energy into healthy competition rather than destructive conflict.",
    reversedMeaning: "Inner conflict, conflict avoidance, tension release. You may be avoiding necessary confrontation or finally finding resolution to ongoing conflict.",
  },
  {
    id: "six-of-wands",
    name: "Six of Wands",
    arcana: "minor",
    suit: "wands",
    number: 6,
    image: "/manus-storage/minor_wands_06_691bcdd8.png",
    keywords: ["success", "public recognition", "progress", "self-confidence"],
    description: "A victorious cat rides through a cheering crowd, wreath of victory upon their head.",
    uprightMeaning: "Success, public recognition, progress, self-confidence. Victory is yours! Enjoy the recognition you have earned and let your confidence shine.",
    reversedMeaning: "Private achievement, fall from grace, egotism. Success may be coming without public recognition, or pride is becoming a stumbling block.",
  },
  {
    id: "seven-of-wands",
    name: "Seven of Wands",
    arcana: "minor",
    suit: "wands",
    number: 7,
    image: "/manus-storage/minor_wands_07_c9034ba6.png",
    keywords: ["challenge", "competition", "protection", "perseverance"],
    description: "A cat stands their ground on a hilltop, defending their position against challengers below.",
    uprightMeaning: "Challenge, competition, protection, perseverance. Stand your ground. You have earned your position — defend it with courage and conviction.",
    reversedMeaning: "Exhaustion, giving up, overwhelmed. You may be feeling overwhelmed by the constant need to defend yourself or your position.",
  },
  {
    id: "eight-of-wands",
    name: "Eight of Wands",
    arcana: "minor",
    suit: "wands",
    number: 8,
    image: "/manus-storage/minor_wands_08_13a1cbc4.png",
    keywords: ["movement", "fast paced change", "action", "alignment"],
    description: "Eight wands fly through the air in swift alignment — rapid movement and swift change.",
    uprightMeaning: "Movement, fast-paced change, action, alignment, air travel. Things are moving quickly now. Ride the momentum and act swiftly.",
    reversedMeaning: "Delays, frustration, resisting change, internal alignment. Movement is being blocked or you are resisting the swift changes unfolding.",
  },
  {
    id: "nine-of-wands",
    name: "Nine of Wands",
    arcana: "minor",
    suit: "wands",
    number: 9,
    image: "/manus-storage/minor_wands_09_3dfeffac.png",
    keywords: ["resilience", "grit", "last stand", "persistence"],
    description: "A battle-weary cat leans on a wand, bandaged but unbroken, ready to face one more challenge.",
    uprightMeaning: "Resilience, grit, last stand, persistence, test of faith. You are almost there. Draw on your reserves of strength — the finish line is near.",
    reversedMeaning: "Inner resources, struggle, overwhelm, defensive. You may be feeling depleted or overly defensive after a long battle.",
  },
  {
    id: "ten-of-wands",
    name: "Ten of Wands",
    arcana: "minor",
    suit: "wands",
    number: 10,
    image: "/manus-storage/minor_wands_10_517fde11.png",
    keywords: ["burden", "extra responsibility", "hard work", "completion"],
    description: "A cat struggles under the weight of ten wands, nearly bent double with the load.",
    uprightMeaning: "Burden, extra responsibility, hard work, completion. You are carrying too much. It is time to delegate, release, or complete what you have taken on.",
    reversedMeaning: "Doing it all, carrying the burden, delegation, release. You may be finally releasing a heavy burden or learning to share the load.",
  },
  {
    id: "page-of-wands",
    name: "Page of Wands",
    arcana: "minor",
    suit: "wands",
    number: 11,
    image: "/manus-storage/minor_wands_page_89908438.png",
    keywords: ["enthusiasm", "exploration", "discovery", "free spirit"],
    description: "A young adventurous cat examines a wand with wide-eyed curiosity and boundless enthusiasm.",
    uprightMeaning: "Enthusiasm, exploration, discovery, free spirit. Embrace your inner adventurer. A new creative endeavor calls with exciting possibilities.",
    reversedMeaning: "Newly-formed ideas, redirecting energy, self-limiting beliefs. Creative energy is present but lacks focus or direction.",
  },
  {
    id: "knight-of-wands",
    name: "Knight of Wands",
    arcana: "minor",
    suit: "wands",
    number: 12,
    image: "/manus-storage/minor_wands_knight_d63fdf72.png",
    keywords: ["energy", "passion", "inspired action", "adventure", "impulsiveness"],
    description: "A daring cat knight charges forward on a rearing horse, wand raised high in passionate pursuit.",
    uprightMeaning: "Energy, passion, inspired action, adventure, impulsiveness. Charge forward with passion and fire. Your enthusiasm is your greatest weapon.",
    reversedMeaning: "Passion project, haste, scattered energy, delays. Impulsiveness may be causing problems — channel your fire more strategically.",
  },
  {
    id: "queen-of-wands",
    name: "Queen of Wands",
    arcana: "minor",
    suit: "wands",
    number: 13,
    image: "/manus-storage/minor_wands_queen_10909cca.png",
    keywords: ["courage", "confidence", "independence", "social butterfly"],
    description: "A magnificent cat queen sits upon a sunflower throne, black cat at her feet, radiating fierce confidence.",
    uprightMeaning: "Courage, confidence, independence, social butterfly, determination. You are a force of nature. Lead with confidence and let your vibrant energy inspire others.",
    reversedMeaning: "Self-respect, self-confidence, introverted, re-establish sense of self. You may be doubting your power or allowing others to dim your radiance.",
  },
  {
    id: "king-of-wands",
    name: "King of Wands",
    arcana: "minor",
    suit: "wands",
    number: 14,
    image: "/manus-storage/minor_wands_king_c82ea0d1.png",
    keywords: ["natural-born leader", "vision", "entrepreneur", "honour"],
    description: "A powerful cat king sits upon a lion-carved throne, wand in hand, a natural-born leader of great vision.",
    uprightMeaning: "Natural-born leader, vision, entrepreneur, honour. Step into your power as a visionary leader. Your charisma and vision can move mountains.",
    reversedMeaning: "Impulsiveness, haste, ruthless, high expectations. Leadership energy is present but may be expressed through arrogance or recklessness.",
  },

  // ── MINOR ARCANA: CUPS ──────────────────────────────────────
  {
    id: "ace-of-cups",
    name: "Ace of Cups",
    arcana: "minor",
    suit: "cups",
    number: 1,
    image: "/manus-storage/minor_cups_ace_3368be2c.png",
    keywords: ["love", "new relationships", "compassion", "creativity"],
    description: "A divine cup overflows with five streams of water — the pure gift of emotional abundance.",
    uprightMeaning: "Love, new relationships, compassion, creativity. Your heart is open and overflowing. A new emotional beginning brings deep joy and connection.",
    reversedMeaning: "Self-love, intuition, repressed emotions. You may be blocking emotional flow or need to turn your compassion inward first.",
  },
  {
    id: "two-of-cups",
    name: "Two of Cups",
    arcana: "minor",
    suit: "cups",
    number: 2,
    image: "/manus-storage/minor_cups_02_3a4da519.png",
    keywords: ["unified love", "partnership", "mutual attraction"],
    description: "Two cats face each other, cups raised in a toast of mutual love and partnership.",
    uprightMeaning: "Unified love, partnership, mutual attraction, relationships. A beautiful union of hearts. This relationship is built on mutual respect and genuine connection.",
    reversedMeaning: "Self-love, break-ups, disharmony, distrust. The connection may be breaking down or one party is not fully committed to the union.",
  },
  {
    id: "three-of-cups",
    name: "Three of Cups",
    arcana: "minor",
    suit: "cups",
    number: 3,
    image: "/manus-storage/minor_cups_03_5c51d1ab.png",
    keywords: ["celebration", "friendship", "creativity", "collaborations"],
    description: "Three cats dance and celebrate together, cups raised in joyful communion.",
    uprightMeaning: "Celebration, friendship, creativity, collaborations. Celebrate with your tribe! Joy, friendship, and creative collaboration are at their peak.",
    reversedMeaning: "Independence, alone time, hardcore partying, three's a crowd. You may need space from social obligations or a friendship triangle is causing tension.",
  },
  {
    id: "four-of-cups",
    name: "Four of Cups",
    arcana: "minor",
    suit: "cups",
    number: 4,
    image: "/manus-storage/minor_cups_04_39729edb.png",
    keywords: ["meditation", "contemplation", "apathy", "reevaluation"],
    description: "A cat sits in contemplation beneath a tree, ignoring three cups before them as a fourth is offered from a cloud.",
    uprightMeaning: "Meditation, contemplation, apathy, reevaluation. Look up from your contemplation — a new opportunity is being offered that you may be missing.",
    reversedMeaning: "Sudden awareness, choosing happiness, acceptance. You are emerging from a period of withdrawal and beginning to see new possibilities.",
  },
  {
    id: "five-of-cups",
    name: "Five of Cups",
    arcana: "minor",
    suit: "cups",
    number: 5,
    image: "/manus-storage/minor_cups_05_f397efde.png",
    keywords: ["regret", "failure", "disappointment", "pessimism"],
    description: "A cloaked cat mourns over three spilled cups, failing to notice the two still standing behind them.",
    uprightMeaning: "Regret, failure, disappointment, pessimism. Acknowledge your grief, but do not let it blind you to what remains. Turn around — not all is lost.",
    reversedMeaning: "Personal setbacks, self-forgiveness, moving on. You are beginning to release grief and find the courage to move forward.",
  },
  {
    id: "six-of-cups",
    name: "Six of Cups",
    arcana: "minor",
    suit: "cups",
    number: 6,
    image: "/manus-storage/minor_cups_06_583ee8f6.png",
    keywords: ["revisiting the past", "childhood memories", "innocence", "joy"],
    description: "A young cat offers a cup of flowers to a smaller kitten — a scene of pure nostalgic innocence.",
    uprightMeaning: "Revisiting the past, childhood memories, innocence, joy. Nostalgia and happy memories bring healing. Reconnect with the joy and innocence of your past.",
    reversedMeaning: "Living in the past, forgiveness, lacking playfulness. You may be too focused on the past or need to forgive old wounds to move forward.",
  },
  {
    id: "seven-of-cups",
    name: "Seven of Cups",
    arcana: "minor",
    suit: "cups",
    number: 7,
    image: "/manus-storage/minor_cups_07_b338cd0d.png",
    keywords: ["opportunities", "choices", "wishful thinking", "illusion"],
    description: "A cat gazes at seven cups floating in clouds, each containing a different vision or temptation.",
    uprightMeaning: "Opportunities, choices, wishful thinking, illusion, fantasy. Many options appear before you, but not all are what they seem. Choose with discernment.",
    reversedMeaning: "Alignment, personal values, overwhelmed by choices. You are cutting through illusion and beginning to see which path truly aligns with your values.",
  },
  {
    id: "eight-of-cups",
    name: "Eight of Cups",
    arcana: "minor",
    suit: "cups",
    number: 8,
    image: "/manus-storage/minor_cups_08_8eeea4f6.png",
    keywords: ["disappointment", "abandonment", "withdrawal", "escapism"],
    description: "A cat walks away from eight carefully stacked cups into the dark mountains, seeking something more.",
    uprightMeaning: "Disappointment, abandonment, withdrawal, escapism. Something that once fulfilled you no longer does. It is time to walk away and seek deeper meaning.",
    reversedMeaning: "Trying one more time, indecision, aimless drifting. You may be struggling to leave behind what no longer serves you, or returning to try once more.",
  },
  {
    id: "nine-of-cups",
    name: "Nine of Cups",
    arcana: "minor",
    suit: "cups",
    number: 9,
    image: "/manus-storage/minor_cups_09_644fe7dc.png",
    keywords: ["contentment", "satisfaction", "gratitude", "wish come true"],
    description: "A satisfied cat sits before nine gleaming cups — the wish card, the card of contentment.",
    uprightMeaning: "Contentment, satisfaction, gratitude, wish come true. Your wish is granted. A period of deep satisfaction and emotional fulfillment is at hand.",
    reversedMeaning: "Inner happiness, materialism, dissatisfaction. External abundance may not be bringing the inner contentment you truly seek.",
  },
  {
    id: "ten-of-cups",
    name: "Ten of Cups",
    arcana: "minor",
    suit: "cups",
    number: 10,
    image: "/manus-storage/minor_cups_10_8749fb5b.png",
    keywords: ["divine love", "blissful relationships", "harmony", "alignment"],
    description: "A cat family stands beneath a rainbow of cups, arms raised in pure joy — the card of lasting happiness.",
    uprightMeaning: "Divine love, blissful relationships, harmony, alignment. The highest expression of emotional fulfillment. True happiness and loving harmony surround you.",
    reversedMeaning: "Disconnection from family, misaligned values, struggling relationships. The dream of perfect harmony is present but something is disrupting the peace.",
  },
  {
    id: "page-of-cups",
    name: "Page of Cups",
    arcana: "minor",
    suit: "cups",
    number: 11,
    image: "/manus-storage/minor_cups_page_2ee5288a.png",
    keywords: ["creative opportunities", "intuitive messages", "curiosity", "possibility"],
    description: "A young cat is surprised by a fish leaping from their cup — a message from the unconscious.",
    uprightMeaning: "Creative opportunities, intuitive messages, curiosity, possibility. An unexpected message or creative inspiration arrives. Stay open to the magical and unusual.",
    reversedMeaning: "New ideas, doubting intuition, creative blocks. You may be dismissing your intuitive messages or struggling to express your creative gifts.",
  },
  {
    id: "knight-of-cups",
    name: "Knight of Cups",
    arcana: "minor",
    suit: "cups",
    number: 12,
    image: "/manus-storage/minor_cups_knight_96474bf1.png",
    keywords: ["creativity", "romance", "charm", "imagination", "beauty"],
    description: "A romantic cat knight rides forth on a white horse, cup held aloft like a chalice of dreams.",
    uprightMeaning: "Creativity, romance, charm, imagination, beauty. A romantic or creative offer arrives. Follow your heart with graceful idealism.",
    reversedMeaning: "Overactive imagination, unrealistic, jealous, moody. Romantic idealism may be clouding your judgment or leading to disappointment.",
  },
  {
    id: "queen-of-cups",
    name: "Queen of Cups",
    arcana: "minor",
    suit: "cups",
    number: 13,
    image: "/manus-storage/minor_cups_queen_6080dc2c.png",
    keywords: ["compassionate", "caring", "emotionally stable", "intuitive", "in flow"],
    description: "A serene cat queen gazes into an ornate covered cup, deeply attuned to the emotional realm.",
    uprightMeaning: "Compassionate, caring, emotionally stable, intuitive, in flow. Lead with compassion and emotional intelligence. Your empathy is your greatest gift.",
    reversedMeaning: "Inner feelings, self-care, self-love, co-dependency. You may be neglecting your own emotional needs while caring for others.",
  },
  {
    id: "king-of-cups",
    name: "King of Cups",
    arcana: "minor",
    suit: "cups",
    number: 14,
    image: "/manus-storage/minor_cups_king_2efcdac4.png",
    keywords: ["emotionally balanced", "compassionate", "diplomatic"],
    description: "A wise cat king sits upon a throne amid turbulent waters, master of his emotional domain.",
    uprightMeaning: "Emotionally balanced, compassionate, diplomatic. Master your emotions with wisdom and grace. Lead from the heart with calm authority.",
    reversedMeaning: "Self-compassion, inner feelings, moodiness, emotionally manipulative. Emotional balance is being disrupted — examine whether feelings are being suppressed or weaponized.",
  },

  // ── MINOR ARCANA: SWORDS ──────────────────────────────────────
  {
    id: "ace-of-swords",
    name: "Ace of Swords",
    arcana: "minor",
    suit: "swords",
    number: 1,
    image: "/manus-storage/minor_swords_ace_d2ff8f99.png",
    keywords: ["breakthroughs", "new ideas", "mental clarity", "success"],
    description: "A gleaming sword emerges from a cloud crowned with victory — the pure force of mental clarity.",
    uprightMeaning: "Breakthroughs, new ideas, mental clarity, success. A breakthrough moment of clarity cuts through confusion. Truth and justice prevail.",
    reversedMeaning: "Inner clarity, re-thinking an idea, clouded judgement. The mental clarity you seek is within, but confusion or miscommunication may be blocking it.",
  },
  {
    id: "two-of-swords",
    name: "Two of Swords",
    arcana: "minor",
    suit: "swords",
    number: 2,
    image: "/manus-storage/minor_swords_02_2dd04b8d.png",
    keywords: ["difficult decisions", "weighing up options", "an impasse", "avoidance"],
    description: "A blindfolded cat holds two crossed swords, caught in a stalemate of indecision.",
    uprightMeaning: "Difficult decisions, weighing up options, an impasse, avoidance. You are at a crossroads. Remove the blindfold and face the decision you have been avoiding.",
    reversedMeaning: "Indecision, confusion, information overload, stalemate. Too much information may be causing paralysis, or you are refusing to see the truth.",
  },
  {
    id: "three-of-swords",
    name: "Three of Swords",
    arcana: "minor",
    suit: "swords",
    number: 3,
    image: "/manus-storage/minor_swords_03_17787495.png",
    keywords: ["heartbreak", "emotional pain", "sorrow", "grief", "hurt"],
    description: "Three swords pierce a heart against a stormy sky — the raw pain of heartbreak.",
    uprightMeaning: "Heartbreak, emotional pain, sorrow, grief, hurt. Acknowledge your pain. Grief is a necessary part of healing — allow yourself to feel it fully.",
    reversedMeaning: "Negative self-talk, releasing pain, optimism, forgiveness. The worst of the pain is passing. Release the grief and allow healing to begin.",
  },
  {
    id: "four-of-swords",
    name: "Four of Swords",
    arcana: "minor",
    suit: "swords",
    number: 4,
    image: "/manus-storage/minor_swords_04_9bbb3a31.png",
    keywords: ["rest", "relaxation", "meditation", "contemplation", "recuperation"],
    description: "A cat lies in peaceful repose on a stone tomb, three swords above, one below — rest after battle.",
    uprightMeaning: "Rest, relaxation, meditation, contemplation, recuperation. You need to rest and restore. Step back from the battle and allow yourself to heal.",
    reversedMeaning: "Restlessness, burnout, stress, need to escape. You may be pushing yourself too hard or struggling to find the rest you desperately need.",
  },
  {
    id: "five-of-swords",
    name: "Five of Swords",
    arcana: "minor",
    suit: "swords",
    number: 5,
    image: "/manus-storage/minor_swords_05_4e40f2bb.png",
    keywords: ["conflict", "disagreements", "competition", "defeat", "winning at all costs"],
    description: "A cat holds three swords while two others walk away in defeat — a hollow victory.",
    uprightMeaning: "Conflict, disagreements, competition, defeat, winning at all costs. Not every battle is worth winning. Consider whether the cost of victory is too high.",
    reversedMeaning: "Reconciliation, making amends, past resentment. Healing is possible after this conflict — are you willing to make amends?",
  },
  {
    id: "six-of-swords",
    name: "Six of Swords",
    arcana: "minor",
    suit: "swords",
    number: 6,
    image: "/manus-storage/minor_swords_06_b8f3c7bd.png",
    keywords: ["transition", "change", "rite of passage", "releasing baggage"],
    description: "A cat ferryman guides passengers from turbulent to calm waters — a journey toward peace.",
    uprightMeaning: "Transition, change, rite of passage, releasing baggage. You are moving from turbulence to calmer waters. Release the past and embrace the journey ahead.",
    reversedMeaning: "Personal transition, resistance to change, unfinished business. You may be resisting a necessary transition or carrying too much baggage from the past.",
  },
  {
    id: "seven-of-swords",
    name: "Seven of Swords",
    arcana: "minor",
    suit: "swords",
    number: 7,
    image: "/manus-storage/minor_swords_07_e51a8cb4.png",
    keywords: ["betrayal", "deception", "getting away with something", "acting strategically"],
    description: "A sneaky cat tiptoes away from a camp carrying five swords — cunning and deception.",
    uprightMeaning: "Betrayal, deception, getting away with something, acting strategically. Beware of deception — either from others or within yourself. Strategy may be necessary.",
    reversedMeaning: "Imposter syndrome, self-deceit, keeping secrets. Hidden truths are coming to light. Face what you have been avoiding or concealing.",
  },
  {
    id: "eight-of-swords",
    name: "Eight of Swords",
    arcana: "minor",
    suit: "swords",
    number: 8,
    image: "/manus-storage/minor_swords_08_62f4cfd6.png",
    keywords: ["negative thoughts", "self-imposed restriction", "imprisonment", "victim mentality"],
    description: "A bound and blindfolded cat stands surrounded by swords — trapped by their own mind.",
    uprightMeaning: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality. The cage is of your own making. Remove the blindfold and you will see you are free.",
    reversedMeaning: "Self-limiting beliefs, inner critic, releasing negative thoughts. You are beginning to recognize the mental patterns that have kept you trapped.",
  },
  {
    id: "nine-of-swords",
    name: "Nine of Swords",
    arcana: "minor",
    suit: "swords",
    number: 9,
    image: "/manus-storage/minor_swords_09_4193b60e.png",
    keywords: ["anxiety", "worry", "fear", "depression", "nightmares"],
    description: "A cat sits up in bed in the dark of night, head in paws, tormented by anxious thoughts.",
    uprightMeaning: "Anxiety, worry, fear, depression, nightmares. The fears that haunt you at night are often worse than reality. Seek support and face your fears in the light of day.",
    reversedMeaning: "Inner turmoil, deep-seated fears, secrets, releasing worry. You are confronting your deepest fears and beginning the process of release and healing.",
  },
  {
    id: "ten-of-swords",
    name: "Ten of Swords",
    arcana: "minor",
    suit: "swords",
    number: 10,
    image: "/manus-storage/minor_swords_10_80eeec77.png",
    keywords: ["painful endings", "deep wounds", "betrayal", "loss", "crisis"],
    description: "A cat lies with ten swords in their back as dawn breaks on the horizon — the darkest moment before the light.",
    uprightMeaning: "Painful endings, deep wounds, betrayal, loss, crisis. This is the darkest hour before the dawn. The worst is over — now the healing can begin.",
    reversedMeaning: "Recovery, regeneration, resisting an inevitable end. You are pulling yourself up from rock bottom. The only way now is up.",
  },
  {
    id: "page-of-swords",
    name: "Page of Swords",
    arcana: "minor",
    suit: "swords",
    number: 11,
    image: "/manus-storage/minor_swords_page_e9745347.png",
    keywords: ["new ideas", "curiosity", "thirst for knowledge", "new ways of communicating"],
    description: "A young alert cat stands on a windswept hilltop, sword raised, keen eyes scanning the horizon.",
    uprightMeaning: "New ideas, curiosity, thirst for knowledge, new ways of communicating. A sharp and curious mind brings new ideas and perspectives. Stay alert and gather information.",
    reversedMeaning: "Self-expression, all talk and no action, haphazard action, haste. Ideas are plentiful but follow-through is lacking. Beware of gossip or hasty decisions.",
  },
  {
    id: "knight-of-swords",
    name: "Knight of Swords",
    arcana: "minor",
    suit: "swords",
    number: 12,
    image: "/manus-storage/minor_swords_knight_fe3544a8.png",
    keywords: ["ambition", "action", "drive", "fearless"],
    description: "A cat knight charges forward on a white horse through a storm, sword raised, utterly fearless.",
    uprightMeaning: "Ambition, action, drive, fearless. Charge forward with fearless determination. Your sharp mind and bold action will cut through any obstacle.",
    reversedMeaning: "Restless, unfocused, impulsive, burn out. Impulsive action without strategy may be causing chaos. Slow down and think before striking.",
  },
  {
    id: "queen-of-swords",
    name: "Queen of Swords",
    arcana: "minor",
    suit: "swords",
    number: 13,
    image: "/manus-storage/minor_swords_queen_35ea982e.png",
    keywords: ["independent", "unbiased judgement", "clear boundaries", "direct communication"],
    description: "A sharp-eyed cat queen sits upon a throne of butterflies, sword upright, mind clear as crystal.",
    uprightMeaning: "Independent, unbiased judgement, clear boundaries, direct communication. Cut through sentiment with clear-eyed truth. Your sharp intellect is your greatest asset.",
    reversedMeaning: "Overly-emotional, easily influenced, bitchy, cold-hearted. Emotional wounds may be causing you to be overly harsh or, conversely, clouding your judgment.",
  },
  {
    id: "king-of-swords",
    name: "King of Swords",
    arcana: "minor",
    suit: "swords",
    number: 14,
    image: "/manus-storage/minor_swords_king_49167366.png",
    keywords: ["mental clarity", "intellectual power", "authority", "truth"],
    description: "An authoritative cat king sits upon a stone throne, sword upright, the embodiment of intellectual authority.",
    uprightMeaning: "Mental clarity, intellectual power, authority, truth. Lead with intellectual clarity and moral authority. Your sharp mind and fair judgment command respect.",
    reversedMeaning: "Quiet power, inner truth, misuse of power, manipulation. Intellectual power may be being used manipulatively or your own inner authority is being suppressed.",
  },

  // ── MINOR ARCANA: PENTACLES ──────────────────────────────────
  {
    id: "ace-of-pentacles",
    name: "Ace of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 1,
    image: "/manus-storage/minor_pentacles_ace_4a4d4cc5.png",
    keywords: ["opportunity", "prosperity", "new ventures", "manifestation"],
    description: "A divine hand offers a gleaming pentacle over a lush garden — pure material potential.",
    uprightMeaning: "Opportunity, prosperity, new ventures, manifestation. A golden opportunity for material abundance arrives. Plant this seed and watch it grow.",
    reversedMeaning: "Lost opportunity, lack of planning and foresight. A material opportunity may be slipping away due to lack of preparation or poor timing.",
  },
  {
    id: "two-of-pentacles",
    name: "Two of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 2,
    image: "/manus-storage/minor_pentacles_02_fda5c1bc.png",
    keywords: ["multiple priorities", "time management", "prioritisation", "adaptability"],
    description: "A nimble cat juggles two pentacles connected by an infinity loop amid turbulent seas.",
    uprightMeaning: "Multiple priorities, time management, prioritisation, adaptability. You are juggling many things at once. Find your rhythm and maintain balance amid the chaos.",
    reversedMeaning: "Over-committed, disorganisation, reprioritisation. You may be taking on more than you can handle — it is time to reassess your priorities.",
  },
  {
    id: "three-of-pentacles",
    name: "Three of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 3,
    image: "/manus-storage/minor_pentacles_03_334216e3.png",
    keywords: ["teamwork", "collaboration", "learning", "implementation"],
    description: "A craftsman cat works on a cathedral arch while colleagues consult plans — mastery through collaboration.",
    uprightMeaning: "Teamwork, collaboration, learning, implementation. Working together creates something greater than any individual effort. Collaborate and learn from others.",
    reversedMeaning: "Disharmony, misalignment, working alone. Team dynamics may be breaking down or you are struggling to integrate your skills with others.",
  },
  {
    id: "four-of-pentacles",
    name: "Four of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 4,
    image: "/manus-storage/minor_pentacles_04_b27723ee.png",
    keywords: ["saving money", "security", "conservatism", "scarcity", "control"],
    description: "A miserly cat clutches pentacles tightly, one on their head, one under each foot — hoarding security.",
    uprightMeaning: "Saving money, security, conservatism, scarcity, control. Financial security is important, but clinging too tightly to what you have may prevent growth.",
    reversedMeaning: "Over-spending, greed, self-protection, generosity. You may be releasing financial control — either through generosity or through reckless spending.",
  },
  {
    id: "five-of-pentacles",
    name: "Five of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 5,
    image: "/manus-storage/minor_pentacles_05_2000bac8.png",
    keywords: ["financial loss", "poverty", "lack mindset", "isolation", "worry"],
    description: "Two ragged cats trudge through snow past a warm church window — hardship and spiritual poverty.",
    uprightMeaning: "Financial loss, poverty, lack mindset, isolation, worry. A difficult period of material hardship. Remember that help is available — look up and seek support.",
    reversedMeaning: "Recovery from financial loss, spiritual poverty, isolation. The worst of the hardship is passing. You are finding your way back to stability.",
  },
  {
    id: "six-of-pentacles",
    name: "Six of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 6,
    image: "/manus-storage/minor_pentacles_06_b1628da2.png",
    keywords: ["giving", "receiving", "sharing wealth", "generosity", "charity"],
    description: "A wealthy cat distributes coins from a balanced scale to those in need — the flow of abundance.",
    uprightMeaning: "Giving, receiving, sharing wealth, generosity, charity. Abundance flows when it is shared. Give generously and receive gracefully.",
    reversedMeaning: "Self-care, unpaid debts, one-sided charity. Generosity may be one-sided or you may be giving from a place of depletion rather than abundance.",
  },
  {
    id: "seven-of-pentacles",
    name: "Seven of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 7,
    image: "/manus-storage/minor_pentacles_07_ab07e963.png",
    keywords: ["long-term view", "sustainable results", "perseverance", "investment"],
    description: "A farmer cat pauses to contemplate the pentacles growing on their vine — patient investment.",
    uprightMeaning: "Long-term view, sustainable results, perseverance, investment. Your patient efforts are bearing fruit. Take stock of your progress and plan for long-term growth.",
    reversedMeaning: "Lack of long-term vision, limited success or reward. You may be impatient for results or investing your energy in the wrong direction.",
  },
  {
    id: "eight-of-pentacles",
    name: "Eight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 8,
    image: "/manus-storage/minor_pentacles_08_5118c803.png",
    keywords: ["apprenticeship", "repetitive tasks", "mastery", "skill development"],
    description: "A diligent cat craftsman works carefully on pentacle after pentacle — the path of mastery.",
    uprightMeaning: "Apprenticeship, repetitive tasks, mastery, skill development. Dedicate yourself to your craft. Mastery comes through focused, diligent practice.",
    reversedMeaning: "Self-development, perfectionism, misdirected activity. You may be obsessing over perfection or applying your skills in the wrong direction.",
  },
  {
    id: "nine-of-pentacles",
    name: "Nine of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 9,
    image: "/manus-storage/minor_pentacles_09_4834085a.png",
    keywords: ["abundance", "luxury", "self-sufficiency", "financial independence"],
    description: "An elegant self-sufficient cat stands in a lush vineyard with a hooded falcon — the pinnacle of material achievement.",
    uprightMeaning: "Abundance, luxury, self-sufficiency, financial independence. You have achieved a beautiful level of self-sufficiency. Enjoy the fruits of your hard work.",
    reversedMeaning: "Self-worth, over-investment in work, hustling. You may be defining your worth by your material achievements or working too hard to enjoy what you have.",
  },
  {
    id: "ten-of-pentacles",
    name: "Ten of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 10,
    image: "/manus-storage/minor_pentacles_10_4da06cea.png",
    keywords: ["wealth", "financial security", "family", "long-term success", "contribution"],
    description: "An elder cat surrounded by family and kittens beneath pentacles arranged in the Tree of Life — lasting legacy.",
    uprightMeaning: "Wealth, financial security, family, long-term success, contribution. The highest expression of material abundance — a lasting legacy built for generations.",
    reversedMeaning: "The dark side of wealth, financial failure or loss, family disputes. The foundations of security may be cracking — examine what truly matters.",
  },
  {
    id: "page-of-pentacles",
    name: "Page of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 11,
    image: "/manus-storage/minor_pentacles_page_a0752c3b.png",
    keywords: ["manifestation", "financial opportunity", "skill development"],
    description: "A studious young cat gazes at a pentacle in a flowering meadow — the eager student of material mastery.",
    uprightMeaning: "Manifestation, financial opportunity, skill development. A new opportunity for learning and material growth arrives. Approach it with curiosity and dedication.",
    reversedMeaning: "Lack of progress, procrastination, learn from failure. You may be procrastinating on developing your skills or failing to take practical action.",
  },
  {
    id: "knight-of-pentacles",
    name: "Knight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 12,
    image: "/manus-storage/minor_pentacles_knight_969d825d.png",
    keywords: ["hard work", "productivity", "routine", "conservatism"],
    description: "A steady cat knight on a black horse surveys a plowed field — methodical, reliable, and utterly dependable.",
    uprightMeaning: "Hard work, productivity, routine, conservatism. Slow and steady wins the race. Your methodical approach and dedication will bring lasting results.",
    reversedMeaning: "Self-discipline, boredom, feeling stuck, perfectionism. You may be stuck in a rut or so focused on routine that you have lost sight of the bigger picture.",
  },
  {
    id: "queen-of-pentacles",
    name: "Queen of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 13,
    image: "/manus-storage/minor_pentacles_queen_4b44cf23.png",
    keywords: ["nurturing", "practical", "providing financially", "a working parent"],
    description: "A nurturing cat queen cradles a pentacle in a lush garden, a rabbit peeking from the bushes.",
    uprightMeaning: "Nurturing, practical, providing financially, a working parent. Nurture yourself and others with practical love and abundant generosity.",
    reversedMeaning: "Financial independence, self-care, work-home conflict. You may be neglecting your own needs while providing for others, or struggling to balance work and home.",
  },
  {
    id: "king-of-pentacles",
    name: "King of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    number: 14,
    image: "/manus-storage/minor_pentacles_king_08b8d0df.png",
    keywords: ["abundance", "prosperity", "security", "ambition", "reliable"],
    description: "A prosperous cat king sits upon a throne of vines and bull heads, holding scepter and pentacle — the master of material abundance.",
    uprightMeaning: "Abundance, prosperity, security, ambition, reliable. You have mastered the material world. Lead with generosity and build lasting prosperity for all.",
    reversedMeaning: "Financially inept, obsessed with wealth and status, stubborn. Material success may be coming at the cost of other values, or financial mismanagement threatens stability.",
  },
];
