export type TarotSuit = "major" | "wands" | "cups" | "swords" | "pentacles";

export interface TarotCard {
  id: string;
  name: string;
  suit: TarotSuit;
  number: number; // 0-21 for major, 1-14 for minor (14=king)
  imageUrl: string;
  uprightMeaning: string;
  reversedMeaning: string;
  keywords: string[];
  element?: string;
  description: string;
}

export const TAROT_CARDS: TarotCard[] = [
  // ── MAJOR ARCANA ──────────────────────────────────────────────────────────
  {
    id: "major_00_fool",
    name: "The Fool",
    suit: "major",
    number: 0,
    imageUrl: "/manus-storage/card_the_fool_dac5159c.png",
    uprightMeaning: "New beginnings, innocence, spontaneity, a free spirit",
    reversedMeaning: "Holding back, recklessness, risk-taking, foolishness",
    keywords: ["beginnings", "innocence", "adventure", "spontaneity"],
    element: "Air",
    description: "The Fool represents the start of a new journey, full of potential and wonder.",
  },
  {
    id: "major_01_magician",
    name: "The Magician",
    suit: "major",
    number: 1,
    imageUrl: "/manus-storage/card_the_magician_0233a16c.png",
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action",
    reversedMeaning: "Manipulation, poor planning, untapped talents",
    keywords: ["willpower", "manifestation", "skill", "action"],
    element: "Air",
    description: "The Magician channels the universe's energy to manifest desires into reality.",
  },
  {
    id: "major_02_high_priestess",
    name: "The High Priestess",
    suit: "major",
    number: 2,
    imageUrl: "/manus-storage/card_high_priestess_57bc5481.png",
    uprightMeaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal",
    keywords: ["intuition", "mystery", "inner knowledge", "subconscious"],
    element: "Water",
    description: "The High Priestess guards the threshold between the conscious and unconscious realms.",
  },
  {
    id: "major_03_empress",
    name: "The Empress",
    suit: "major",
    number: 3,
    imageUrl: "/manus-storage/card_the_empress_73fbf66d.png",
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance",
    reversedMeaning: "Creative block, dependence on others, smothering",
    keywords: ["abundance", "fertility", "nature", "nurturing"],
    element: "Earth",
    description: "The Empress embodies the fertile abundance of nature and the nurturing power of creation.",
  },
  {
    id: "major_04_emperor",
    name: "The Emperor",
    suit: "major",
    number: 4,
    imageUrl: "/manus-storage/card_the_emperor_1149a424.png",
    uprightMeaning: "Authority, establishment, structure, a father figure",
    reversedMeaning: "Domination, excessive control, lack of discipline, inflexibility",
    keywords: ["authority", "structure", "stability", "leadership"],
    element: "Fire",
    description: "The Emperor represents the power of order, structure, and paternal authority.",
  },
  {
    id: "major_05_hierophant",
    name: "The Hierophant",
    suit: "major",
    number: 5,
    imageUrl: "/manus-storage/card_the_hierophant_78ad8ac6.png",
    uprightMeaning: "Spiritual wisdom, religious beliefs, conformity, tradition",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo",
    keywords: ["tradition", "conformity", "morality", "ethics"],
    element: "Earth",
    description: "The Hierophant bridges the divine and the earthly, guiding through tradition and wisdom.",
  },
  {
    id: "major_06_lovers",
    name: "The Lovers",
    suit: "major",
    number: 6,
    imageUrl: "/manus-storage/card_the_lovers_b4e268a8.png",
    uprightMeaning: "Love, harmony, relationships, values alignment, choices",
    reversedMeaning: "Self-love, disharmony, imbalance, misaligned values",
    keywords: ["love", "union", "choices", "alignment"],
    element: "Air",
    description: "The Lovers speak of deep connection, meaningful choices, and the harmony of union.",
  },
  {
    id: "major_07_chariot",
    name: "The Chariot",
    suit: "major",
    number: 7,
    imageUrl: "/manus-storage/card_the_chariot_0e894191.png",
    uprightMeaning: "Control, willpower, success, action, determination",
    reversedMeaning: "Self-discipline, opposition, lack of direction",
    keywords: ["determination", "control", "victory", "willpower"],
    element: "Water",
    description: "The Chariot charges forward with fierce determination, harnessing opposing forces toward victory.",
  },
  {
    id: "major_08_strength",
    name: "Strength",
    suit: "major",
    number: 8,
    imageUrl: "/manus-storage/card_strength_8e9a89fe.png",
    uprightMeaning: "Strength, courage, persuasion, influence, compassion",
    reversedMeaning: "Inner strength, self-doubt, low energy, raw emotion",
    keywords: ["courage", "patience", "compassion", "inner strength"],
    element: "Fire",
    description: "Strength tames the wild beast within through gentle courage and compassionate resolve.",
  },
  {
    id: "major_09_hermit",
    name: "The Hermit",
    suit: "major",
    number: 9,
    imageUrl: "/manus-storage/card_the_hermit_99716f4b.png",
    uprightMeaning: "Soul-searching, introspection, being alone, inner guidance",
    reversedMeaning: "Isolation, loneliness, withdrawal, lost your way",
    keywords: ["solitude", "introspection", "guidance", "wisdom"],
    element: "Earth",
    description: "The Hermit withdraws from the world to seek the lantern of inner wisdom.",
  },
  {
    id: "major_10_wheel",
    name: "Wheel of Fortune",
    suit: "major",
    number: 10,
    imageUrl: "/manus-storage/card_wheel_of_fortune_61b45ff7.png",
    uprightMeaning: "Good luck, karma, life cycles, destiny, a turning point",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles",
    keywords: ["fate", "cycles", "luck", "destiny"],
    element: "Fire",
    description: "The Wheel of Fortune turns ceaselessly, reminding us that all things are cyclical.",
  },
  {
    id: "major_11_justice",
    name: "Justice",
    suit: "major",
    number: 11,
    imageUrl: "/manus-storage/card_justice_e2709f02.png",
    uprightMeaning: "Justice, fairness, truth, cause and effect, law",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty",
    keywords: ["truth", "fairness", "law", "cause and effect"],
    element: "Air",
    description: "Justice holds the scales of truth, ensuring that all actions meet their rightful consequence.",
  },
  {
    id: "major_12_hanged_man",
    name: "The Hanged Man",
    suit: "major",
    number: 12,
    imageUrl: "/manus-storage/card_the_hanged_man_44476862.png",
    uprightMeaning: "Pause, surrender, letting go, new perspectives",
    reversedMeaning: "Delays, resistance, stalling, indecision",
    keywords: ["surrender", "pause", "perspective", "sacrifice"],
    element: "Water",
    description: "The Hanged Man suspends himself willingly, gaining enlightenment through surrender.",
  },
  {
    id: "major_13_death",
    name: "Death",
    suit: "major",
    number: 13,
    imageUrl: "/manus-storage/card_death_a36b7ec7.png",
    uprightMeaning: "Endings, change, transformation, transition",
    reversedMeaning: "Resistance to change, personal transformation, inner purging",
    keywords: ["transformation", "endings", "change", "transition"],
    element: "Water",
    description: "Death heralds not an end but a profound transformation — the closing of one chapter and opening of another.",
  },
  {
    id: "major_14_temperance",
    name: "Temperance",
    suit: "major",
    number: 14,
    imageUrl: "/manus-storage/card_temperance_48f57473.png",
    uprightMeaning: "Balance, moderation, patience, purpose, meaning",
    reversedMeaning: "Imbalance, excess, self-healing, re-alignment",
    keywords: ["balance", "patience", "moderation", "purpose"],
    element: "Fire",
    description: "Temperance pours the waters of life between two vessels, finding perfect equilibrium.",
  },
  {
    id: "major_15_devil",
    name: "The Devil",
    suit: "major",
    number: 15,
    imageUrl: "/manus-storage/card_the_devil_3feb397f.png",
    uprightMeaning: "Shadow self, attachment, addiction, restriction, sexuality",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts, detachment",
    keywords: ["bondage", "addiction", "materialism", "shadow"],
    element: "Earth",
    description: "The Devil reveals the chains we forge ourselves — attachments and illusions that bind the spirit.",
  },
  {
    id: "major_16_tower",
    name: "The Tower",
    suit: "major",
    number: 16,
    imageUrl: "/manus-storage/card_the_tower_cb0741df.png",
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening",
    reversedMeaning: "Personal transformation, fear of change, averting disaster",
    keywords: ["upheaval", "chaos", "revelation", "disruption"],
    element: "Fire",
    description: "The Tower is struck by lightning, shattering false structures to reveal the truth beneath.",
  },
  {
    id: "major_17_star",
    name: "The Star",
    suit: "major",
    number: 17,
    imageUrl: "/manus-storage/card_the_star_2f718c37.png",
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality",
    reversedMeaning: "Lack of faith, despair, self-trust, disconnection",
    keywords: ["hope", "inspiration", "serenity", "renewal"],
    element: "Air",
    description: "The Star pours healing waters under a canopy of stars, offering hope and divine guidance.",
  },
  {
    id: "major_18_moon",
    name: "The Moon",
    suit: "major",
    number: 18,
    imageUrl: "/manus-storage/card_the_moon_7ca495a4.png",
    uprightMeaning: "Illusion, fear, the unconscious, intuition, confusion",
    reversedMeaning: "Release of fear, repressed emotion, inner confusion",
    keywords: ["illusion", "fear", "subconscious", "dreams"],
    element: "Water",
    description: "The Moon casts shifting shadows, blurring the line between reality and dream.",
  },
  {
    id: "major_19_sun",
    name: "The Sun",
    suit: "major",
    number: 19,
    imageUrl: "/manus-storage/card_the_sun_3a1cedd5.png",
    uprightMeaning: "Positivity, fun, warmth, success, vitality",
    reversedMeaning: "Inner child, feeling down, overly optimistic",
    keywords: ["joy", "success", "vitality", "optimism"],
    element: "Fire",
    description: "The Sun blazes with radiant joy, illuminating all with warmth, clarity, and abundance.",
  },
  {
    id: "major_20_judgement",
    name: "Judgement",
    suit: "major",
    number: 20,
    imageUrl: "/manus-storage/card_judgement_54e4c47d.png",
    uprightMeaning: "Judgement, rebirth, inner calling, absolution",
    reversedMeaning: "Self-doubt, inner critic, ignoring the call",
    keywords: ["rebirth", "absolution", "awakening", "reckoning"],
    element: "Fire",
    description: "Judgement calls the soul to rise and answer the higher calling of its true purpose.",
  },
  {
    id: "major_21_world",
    name: "The World",
    suit: "major",
    number: 21,
    imageUrl: "/manus-storage/card_the_world_07a37fee.png",
    uprightMeaning: "Completion, integration, accomplishment, travel",
    reversedMeaning: "Seeking personal closure, short-cuts, delays",
    keywords: ["completion", "wholeness", "achievement", "integration"],
    element: "Earth",
    description: "The World marks the triumphant completion of the great cycle — wholeness achieved.",
  },

  // ── WANDS ─────────────────────────────────────────────────────────────────
  {
    id: "wands_01_ace",
    name: "Ace of Wands",
    suit: "wands",
    number: 1,
    imageUrl: "/manus-storage/minor_wands_ace_53180df0.png",
    uprightMeaning: "Inspiration, new opportunities, growth, potential",
    reversedMeaning: "An emerging idea, lack of direction, distractions",
    keywords: ["inspiration", "potential", "new beginnings", "spark"],
    element: "Fire",
    description: "The Ace of Wands ignites a spark of pure creative potential and passionate new beginnings.",
  },
  {
    id: "wands_02",
    name: "Two of Wands",
    suit: "wands",
    number: 2,
    imageUrl: "/manus-storage/minor_wands_02_5b708043.png",
    uprightMeaning: "Future planning, progress, decisions, discovery",
    reversedMeaning: "Personal goals, inner alignment, fear of unknown",
    keywords: ["planning", "vision", "progress", "discovery"],
    element: "Fire",
    description: "The Two of Wands surveys the horizon, planning the bold journey that lies ahead.",
  },
  {
    id: "wands_03",
    name: "Three of Wands",
    suit: "wands",
    number: 3,
    imageUrl: "/manus-storage/minor_wands_03_bcb3e460.png",
    uprightMeaning: "Progress, expansion, foresight, overseas opportunities",
    reversedMeaning: "Playing small, lack of foresight, unexpected delays",
    keywords: ["expansion", "foresight", "enterprise", "exploration"],
    element: "Fire",
    description: "The Three of Wands watches ships sail forth, signaling expansion and the fruits of early efforts.",
  },
  {
    id: "wands_04",
    name: "Four of Wands",
    suit: "wands",
    number: 4,
    imageUrl: "/manus-storage/minor_wands_04_085cbd45.png",
    uprightMeaning: "Celebration, joy, harmony, relaxation, homecoming",
    reversedMeaning: "Personal celebration, inner harmony, conflict with others",
    keywords: ["celebration", "harmony", "homecoming", "community"],
    element: "Fire",
    description: "The Four of Wands raises a joyful canopy, celebrating milestones and the warmth of belonging.",
  },
  {
    id: "wands_05",
    name: "Five of Wands",
    suit: "wands",
    number: 5,
    imageUrl: "/manus-storage/minor_wands_05_f124c964.png",
    uprightMeaning: "Conflict, disagreements, competition, tension, diversity",
    reversedMeaning: "Inner conflict, conflict avoidance, tension release",
    keywords: ["conflict", "competition", "struggle", "diversity"],
    element: "Fire",
    description: "The Five of Wands depicts a spirited clash of competing energies and viewpoints.",
  },
  {
    id: "wands_06",
    name: "Six of Wands",
    suit: "wands",
    number: 6,
    imageUrl: "/manus-storage/minor_wands_06_a9d5d5bb.png",
    uprightMeaning: "Success, public recognition, progress, self-confidence",
    reversedMeaning: "Private achievement, personal definition of success, fall from grace",
    keywords: ["victory", "recognition", "confidence", "triumph"],
    element: "Fire",
    description: "The Six of Wands rides in triumph, crowned with the laurels of hard-won victory.",
  },
  {
    id: "wands_07",
    name: "Seven of Wands",
    suit: "wands",
    number: 7,
    imageUrl: "/manus-storage/minor_wands_07_d0586fb8.png",
    uprightMeaning: "Challenge, competition, protection, perseverance",
    reversedMeaning: "Exhaustion, giving up, overwhelmed",
    keywords: ["perseverance", "defense", "challenge", "determination"],
    element: "Fire",
    description: "The Seven of Wands stands firm against opposition, defending hard-won ground with courage.",
  },
  {
    id: "wands_08",
    name: "Eight of Wands",
    suit: "wands",
    number: 8,
    imageUrl: "/manus-storage/minor_wands_08_1c4dc8f8.png",
    uprightMeaning: "Movement, fast paced change, action, alignment, air travel",
    reversedMeaning: "Delays, frustration, resisting change, internal alignment",
    keywords: ["speed", "action", "movement", "swift change"],
    element: "Fire",
    description: "The Eight of Wands streaks through the sky — swift action, rapid progress, and momentum.",
  },
  {
    id: "wands_09",
    name: "Nine of Wands",
    suit: "wands",
    number: 9,
    imageUrl: "/manus-storage/minor_wands_09_8fa48e10.png",
    uprightMeaning: "Resilience, grit, last stand, persistence, test of faith",
    reversedMeaning: "Inner resources, struggle, overwhelm, defensive",
    keywords: ["resilience", "persistence", "stamina", "last stand"],
    element: "Fire",
    description: "The Nine of Wands stands battle-worn but unbroken, summoning final reserves of strength.",
  },
  {
    id: "wands_10",
    name: "Ten of Wands",
    suit: "wands",
    number: 10,
    imageUrl: "/manus-storage/minor_wands_10_4c831513.png",
    uprightMeaning: "Burden, extra responsibility, hard work, completion",
    reversedMeaning: "Doing it all, carrying the burden, delegation, release",
    keywords: ["burden", "responsibility", "hard work", "oppression"],
    element: "Fire",
    description: "The Ten of Wands bears a heavy load, the weight of accumulated responsibilities nearing completion.",
  },
  {
    id: "wands_11_page",
    name: "Page of Wands",
    suit: "wands",
    number: 11,
    imageUrl: "/manus-storage/minor_wands_page_7f3ee222.png",
    uprightMeaning: "Inspiration, ideas, discovery, limitless potential, free spirit",
    reversedMeaning: "Newly-formed ideas, redirecting energy, self-limiting beliefs",
    keywords: ["enthusiasm", "exploration", "discovery", "free spirit"],
    element: "Fire",
    description: "The Page of Wands brims with youthful enthusiasm, eager to explore every new horizon.",
  },
  {
    id: "wands_12_knight",
    name: "Knight of Wands",
    suit: "wands",
    number: 12,
    imageUrl: "/manus-storage/minor_wands_knight_e7c56a5e.png",
    uprightMeaning: "Energy, passion, inspired action, adventure, impulsiveness",
    reversedMeaning: "Passion project, haste, scattered energy, delays",
    keywords: ["action", "adventure", "passion", "impulsiveness"],
    element: "Fire",
    description: "The Knight of Wands charges forward with passionate, unstoppable energy and daring spirit.",
  },
  {
    id: "wands_13_queen",
    name: "Queen of Wands",
    suit: "wands",
    number: 13,
    imageUrl: "/manus-storage/minor_wands_queen_dea2c8f6.png",
    uprightMeaning: "Courage, confidence, independence, social butterfly, determination",
    reversedMeaning: "Self-respect, self-confidence, introverted, re-establish sense of self",
    keywords: ["confidence", "independence", "charisma", "determination"],
    element: "Fire",
    description: "The Queen of Wands radiates magnetic confidence and fierce, creative independence.",
  },
  {
    id: "wands_14_king",
    name: "King of Wands",
    suit: "wands",
    number: 14,
    imageUrl: "/manus-storage/minor_wands_king_4b83fd94.png",
    uprightMeaning: "Natural-born leader, vision, entrepreneur, honour",
    reversedMeaning: "Impulsiveness, haste, ruthless, high expectations",
    keywords: ["leadership", "vision", "boldness", "entrepreneurship"],
    element: "Fire",
    description: "The King of Wands commands with bold vision and the natural authority of a born leader.",
  },

  // ── CUPS ──────────────────────────────────────────────────────────────────
  {
    id: "cups_01_ace",
    name: "Ace of Cups",
    suit: "cups",
    number: 1,
    imageUrl: "/manus-storage/minor_cups_ace_bc0f71df.png",
    uprightMeaning: "Love, new relationships, compassion, creativity",
    reversedMeaning: "Self-love, intuition, repressed emotions",
    keywords: ["love", "new feelings", "compassion", "creativity"],
    element: "Water",
    description: "The Ace of Cups overflows with pure emotional potential — the wellspring of love and intuition.",
  },
  {
    id: "cups_02",
    name: "Two of Cups",
    suit: "cups",
    number: 2,
    imageUrl: "/manus-storage/minor_cups_02_ebf697a1.png",
    uprightMeaning: "Unified love, partnership, mutual attraction",
    reversedMeaning: "Self-love, break-ups, disharmony, distrust",
    keywords: ["partnership", "connection", "mutual attraction", "union"],
    element: "Water",
    description: "The Two of Cups toasts a deep and equal partnership, a bond of mutual love and respect.",
  },
  {
    id: "cups_03",
    name: "Three of Cups",
    suit: "cups",
    number: 3,
    imageUrl: "/manus-storage/minor_cups_03_ef758d94.png",
    uprightMeaning: "Celebration, friendship, creativity, collaborations",
    reversedMeaning: "Independence, alone time, hardcore partying, three's a crowd",
    keywords: ["celebration", "friendship", "community", "joy"],
    element: "Water",
    description: "The Three of Cups raises glasses in joyful celebration of friendship and shared abundance.",
  },
  {
    id: "cups_04",
    name: "Four of Cups",
    suit: "cups",
    number: 4,
    imageUrl: "/manus-storage/minor_cups_04_8d8aed0a.png",
    uprightMeaning: "Meditation, contemplation, apathy, reevaluation",
    reversedMeaning: "Retreat, withdrawal, checking in for alignment",
    keywords: ["contemplation", "apathy", "withdrawal", "reevaluation"],
    element: "Water",
    description: "The Four of Cups sits in quiet contemplation, unmoved by the cup offered from the divine.",
  },
  {
    id: "cups_05",
    name: "Five of Cups",
    suit: "cups",
    number: 5,
    imageUrl: "/manus-storage/minor_cups_05_6cbf9ad9.png",
    uprightMeaning: "Regret, failure, disappointment, pessimism",
    reversedMeaning: "Personal setbacks, self-forgiveness, moving on",
    keywords: ["loss", "grief", "regret", "disappointment"],
    element: "Water",
    description: "The Five of Cups mourns what has been spilled, yet two cups behind still stand full.",
  },
  {
    id: "cups_06",
    name: "Six of Cups",
    suit: "cups",
    number: 6,
    imageUrl: "/manus-storage/minor_cups_06_14963fca.png",
    uprightMeaning: "Revisiting the past, childhood memories, innocence, joy",
    reversedMeaning: "Living in the past, forgiveness, lacking playfulness",
    keywords: ["nostalgia", "childhood", "innocence", "memories"],
    element: "Water",
    description: "The Six of Cups offers a bouquet of sweet nostalgia and the innocence of cherished memories.",
  },
  {
    id: "cups_07",
    name: "Seven of Cups",
    suit: "cups",
    number: 7,
    imageUrl: "/manus-storage/minor_cups_07_b557491a.png",
    uprightMeaning: "Opportunities, choices, wishful thinking, illusion",
    reversedMeaning: "Alignment, personal values, overwhelmed by choices",
    keywords: ["fantasy", "illusion", "choices", "wishful thinking"],
    element: "Water",
    description: "The Seven of Cups presents a dazzling array of visions — but which is real and which is illusion?",
  },
  {
    id: "cups_08",
    name: "Eight of Cups",
    suit: "cups",
    number: 8,
    imageUrl: "/manus-storage/minor_cups_08_e9750129.png",
    uprightMeaning: "Disappointment, abandonment, withdrawal, escapism",
    reversedMeaning: "Trying one more time, indecision, aimless drifting",
    keywords: ["withdrawal", "abandonment", "seeking deeper meaning", "walking away"],
    element: "Water",
    description: "The Eight of Cups turns away from what was once cherished, walking toward deeper meaning.",
  },
  {
    id: "cups_09",
    name: "Nine of Cups",
    suit: "cups",
    number: 9,
    imageUrl: "/manus-storage/minor_cups_09_dce0879b.png",
    uprightMeaning: "Contentment, satisfaction, gratitude, wish come true",
    reversedMeaning: "Inner happiness, materialism, dissatisfaction",
    keywords: ["contentment", "satisfaction", "wish fulfillment", "gratitude"],
    element: "Water",
    description: "The Nine of Cups sits before a row of gleaming cups — the wish card, contentment fulfilled.",
  },
  {
    id: "cups_10",
    name: "Ten of Cups",
    suit: "cups",
    number: 10,
    imageUrl: "/manus-storage/minor_cups_10_d683c322.png",
    uprightMeaning: "Divine love, blissful relationships, harmony, alignment",
    reversedMeaning: "Disconnection, misaligned values, struggling relationships",
    keywords: ["harmony", "happiness", "family", "fulfillment"],
    element: "Water",
    description: "The Ten of Cups paints a rainbow of perfect harmony — the ultimate emotional fulfillment.",
  },
  {
    id: "cups_11_page",
    name: "Page of Cups",
    suit: "cups",
    number: 11,
    imageUrl: "/manus-storage/minor_cups_page_163f06b3.png",
    uprightMeaning: "Creative opportunities, intuitive messages, curiosity, possibility",
    reversedMeaning: "New ideas, doubting intuition, creative blocks",
    keywords: ["intuition", "sensitivity", "creativity", "messages"],
    element: "Water",
    description: "The Page of Cups receives a surprising message from the depths of the unconscious.",
  },
  {
    id: "cups_12_knight",
    name: "Knight of Cups",
    suit: "cups",
    number: 12,
    imageUrl: "/manus-storage/minor_cups_knight_d3387ea7.png",
    uprightMeaning: "Creativity, romance, charm, imagination, beauty",
    reversedMeaning: "Overactive imagination, unrealistic, jealous, moody",
    keywords: ["romance", "charm", "idealism", "creativity"],
    element: "Water",
    description: "The Knight of Cups rides forth as a romantic idealist, bearing the cup of heartfelt quests.",
  },
  {
    id: "cups_13_queen",
    name: "Queen of Cups",
    suit: "cups",
    number: 13,
    imageUrl: "/manus-storage/minor_cups_queen_dec09c8f.png",
    uprightMeaning: "Compassionate, caring, emotionally stable, intuitive, in flow",
    reversedMeaning: "Inner feelings, self-care, self-love, co-dependency",
    keywords: ["compassion", "empathy", "intuition", "emotional wisdom"],
    element: "Water",
    description: "The Queen of Cups gazes into her cup with deep empathy, holding the wisdom of the heart.",
  },
  {
    id: "cups_14_king",
    name: "King of Cups",
    suit: "cups",
    number: 14,
    imageUrl: "/manus-storage/minor_cups_king_93cd50ca.png",
    uprightMeaning: "Emotionally balanced, compassionate, diplomatic",
    reversedMeaning: "Self-compassion, inner feelings, moodiness, emotionally manipulative",
    keywords: ["emotional mastery", "diplomacy", "compassion", "wisdom"],
    element: "Water",
    description: "The King of Cups rules the emotional realm with calm authority and deep compassionate wisdom.",
  },

  // ── SWORDS ────────────────────────────────────────────────────────────────
  {
    id: "swords_01_ace",
    name: "Ace of Swords",
    suit: "swords",
    number: 1,
    imageUrl: "/manus-storage/minor_swords_ace_871b027b.png",
    uprightMeaning: "Breakthroughs, new ideas, mental clarity, success",
    reversedMeaning: "Inner clarity, re-thinking an idea, clouded judgement",
    keywords: ["clarity", "truth", "breakthrough", "mental force"],
    element: "Air",
    description: "The Ace of Swords cuts through confusion with the razor edge of pure mental clarity.",
  },
  {
    id: "swords_02",
    name: "Two of Swords",
    suit: "swords",
    number: 2,
    imageUrl: "/manus-storage/minor_swords_02_f4d4e5da.png",
    uprightMeaning: "Difficult decisions, weighing up options, an impasse, avoidance",
    reversedMeaning: "Indecision, confusion, information overload, stalemate",
    keywords: ["indecision", "stalemate", "avoidance", "blocked emotions"],
    element: "Air",
    description: "The Two of Swords sits blindfolded, holding two blades in tense equilibrium — a decision deferred.",
  },
  {
    id: "swords_03",
    name: "Three of Swords",
    suit: "swords",
    number: 3,
    imageUrl: "/manus-storage/minor_swords_03_9550a269.png",
    uprightMeaning: "Heartbreak, emotional pain, sorrow, grief, hurt",
    reversedMeaning: "Negative self-talk, releasing pain, optimism, forgiveness",
    keywords: ["heartbreak", "sorrow", "grief", "pain"],
    element: "Air",
    description: "The Three of Swords pierces the heart with the sharp truth of loss and emotional pain.",
  },
  {
    id: "swords_04",
    name: "Four of Swords",
    suit: "swords",
    number: 4,
    imageUrl: "/manus-storage/minor_swords_04_031bff24.png",
    uprightMeaning: "Rest, relaxation, meditation, contemplation, recuperation",
    reversedMeaning: "Exhaustion, burn-out, deep contemplation, stagnation",
    keywords: ["rest", "recovery", "contemplation", "retreat"],
    element: "Air",
    description: "The Four of Swords lies in peaceful repose, restoring strength through sacred stillness.",
  },
  {
    id: "swords_05",
    name: "Five of Swords",
    suit: "swords",
    number: 5,
    imageUrl: "/manus-storage/minor_swords_05_96532527.png",
    uprightMeaning: "Conflict, disagreements, competition, defeat, winning at all costs",
    reversedMeaning: "Reconciliation, making amends, past resentment",
    keywords: ["conflict", "defeat", "hollow victory", "tension"],
    element: "Air",
    description: "The Five of Swords wins the battle but loses the war, a hollow victory steeped in conflict.",
  },
  {
    id: "swords_06",
    name: "Six of Swords",
    suit: "swords",
    number: 6,
    imageUrl: "/manus-storage/minor_swords_06_57869fd4.png",
    uprightMeaning: "Transition, change, rite of passage, releasing baggage",
    reversedMeaning: "Personal transition, resistance to change, unfinished business",
    keywords: ["transition", "moving on", "travel", "healing"],
    element: "Air",
    description: "The Six of Swords ferries souls across still waters, moving from turbulence toward calmer shores.",
  },
  {
    id: "swords_07",
    name: "Seven of Swords",
    suit: "swords",
    number: 7,
    imageUrl: "/manus-storage/minor_swords_07_a726dd15.png",
    uprightMeaning: "Betrayal, deception, getting away with something, acting strategically",
    reversedMeaning: "Imposter syndrome, self-deceit, keeping secrets",
    keywords: ["deception", "strategy", "stealth", "betrayal"],
    element: "Air",
    description: "The Seven of Swords slips away in the night, carrying blades of cunning and strategic deception.",
  },
  {
    id: "swords_08",
    name: "Eight of Swords",
    suit: "swords",
    number: 8,
    imageUrl: "/manus-storage/minor_swords_08_c246cdd4.png",
    uprightMeaning: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality",
    reversedMeaning: "Self-limiting beliefs, inner critic, releasing negative thoughts",
    keywords: ["restriction", "imprisonment", "self-limitation", "victimhood"],
    element: "Air",
    description: "The Eight of Swords stands blindfolded and bound — yet the chains are of the mind's own making.",
  },
  {
    id: "swords_09",
    name: "Nine of Swords",
    suit: "swords",
    number: 9,
    imageUrl: "/manus-storage/minor_swords_09_1190a536.png",
    uprightMeaning: "Anxiety, worry, fear, depression, nightmares",
    reversedMeaning: "Inner turmoil, deep-seated fears, secrets, releasing worry",
    keywords: ["anxiety", "worry", "nightmares", "despair"],
    element: "Air",
    description: "The Nine of Swords wakes at midnight, tormented by the blades of anxiety and dark thoughts.",
  },
  {
    id: "swords_10",
    name: "Ten of Swords",
    suit: "swords",
    number: 10,
    imageUrl: "/manus-storage/minor_swords_10_c7c5c572.png",
    uprightMeaning: "Painful endings, deep wounds, betrayal, loss, crisis",
    reversedMeaning: "Recovery, regeneration, resisting an inevitable end",
    keywords: ["painful endings", "betrayal", "crisis", "rock bottom"],
    element: "Air",
    description: "The Ten of Swords marks the darkest hour — yet with dawn comes the promise of renewal.",
  },
  {
    id: "swords_11_page",
    name: "Page of Swords",
    suit: "swords",
    number: 11,
    imageUrl: "/manus-storage/minor_swords_page_c65d63ee.png",
    uprightMeaning: "New ideas, curiosity, thirst for knowledge, new ways of communicating",
    reversedMeaning: "Self-expression, all talk and no action, haphazard action",
    keywords: ["curiosity", "wit", "vigilance", "mental agility"],
    element: "Air",
    description: "The Page of Swords stands alert, sword raised, hungry for knowledge and sharp debate.",
  },
  {
    id: "swords_12_knight",
    name: "Knight of Swords",
    suit: "swords",
    number: 12,
    imageUrl: "/manus-storage/minor_swords_knight_81a505e3.png",
    uprightMeaning: "Ambitious, action-oriented, driven to succeed, fast-thinking",
    reversedMeaning: "Restless, unfocused, impulsive, burn-out",
    keywords: ["ambition", "speed", "directness", "assertiveness"],
    element: "Air",
    description: "The Knight of Swords charges headlong into battle, driven by fierce ambition and sharp intellect.",
  },
  {
    id: "swords_13_queen",
    name: "Queen of Swords",
    suit: "swords",
    number: 13,
    imageUrl: "/manus-storage/minor_swords_queen_b130d7bb.png",
    uprightMeaning: "Independent, unbiased judgement, clear boundaries, direct communication",
    reversedMeaning: "Overly-emotional, easily influenced, bitchy, cold-hearted",
    keywords: ["clarity", "independence", "direct truth", "sharp mind"],
    element: "Air",
    description: "The Queen of Swords cuts through pretense with clear-eyed wisdom and uncompromising truth.",
  },
  {
    id: "swords_14_king",
    name: "King of Swords",
    suit: "swords",
    number: 14,
    imageUrl: "/manus-storage/minor_swords_king_1e3a8876.png",
    uprightMeaning: "Mental clarity, intellectual power, authority, truth, ethics",
    reversedMeaning: "Quiet power, inner truth, misuse of power, manipulation",
    keywords: ["intellect", "authority", "truth", "ethics"],
    element: "Air",
    description: "The King of Swords rules with the sword of pure intellect, upholding truth and ethical authority.",
  },

  // ── PENTACLES ─────────────────────────────────────────────────────────────
  {
    id: "pentacles_01_ace",
    name: "Ace of Pentacles",
    suit: "pentacles",
    number: 1,
    imageUrl: "/manus-storage/minor_pentacles_ace_a921d8a1.png",
    uprightMeaning: "A new financial or career opportunity, manifestation, abundance",
    reversedMeaning: "Lost opportunity, lack of planning and foresight",
    keywords: ["opportunity", "prosperity", "abundance", "manifestation"],
    element: "Earth",
    description: "The Ace of Pentacles offers a golden coin of pure material potential — a new beginning in the physical world.",
  },
  {
    id: "pentacles_02",
    name: "Two of Pentacles",
    suit: "pentacles",
    number: 2,
    imageUrl: "/manus-storage/minor_pentacles_02_0627a04b.png",
    uprightMeaning: "Multiple priorities, time management, prioritisation, adaptability",
    reversedMeaning: "Over-committed, disorganisation, reprioritisation",
    keywords: ["balance", "adaptability", "juggling", "flexibility"],
    element: "Earth",
    description: "The Two of Pentacles juggles life's demands with graceful adaptability and rhythmic balance.",
  },
  {
    id: "pentacles_03",
    name: "Three of Pentacles",
    suit: "pentacles",
    number: 3,
    imageUrl: "/manus-storage/minor_pentacles_03_50d434c4.png",
    uprightMeaning: "Teamwork, collaboration, learning, implementation",
    reversedMeaning: "Disharmony, misalignment, working alone",
    keywords: ["collaboration", "craftsmanship", "teamwork", "skill"],
    element: "Earth",
    description: "The Three of Pentacles brings together master craftspeople, each contributing their skill to a greater work.",
  },
  {
    id: "pentacles_04",
    name: "Four of Pentacles",
    suit: "pentacles",
    number: 4,
    imageUrl: "/manus-storage/minor_pentacles_04_e283b1ea.png",
    uprightMeaning: "Saving money, security, conservatism, scarcity, control",
    reversedMeaning: "Over-spending, greed, self-protection",
    keywords: ["security", "control", "conservation", "possessiveness"],
    element: "Earth",
    description: "The Four of Pentacles clutches coins tightly — security sought, but at the cost of openness.",
  },
  {
    id: "pentacles_05",
    name: "Five of Pentacles",
    suit: "pentacles",
    number: 5,
    imageUrl: "/manus-storage/minor_pentacles_05_a88c9de0.png",
    uprightMeaning: "Financial loss, poverty, lack mindset, isolation, worry",
    reversedMeaning: "Recovery from financial loss, spiritual poverty",
    keywords: ["hardship", "poverty", "isolation", "adversity"],
    element: "Earth",
    description: "The Five of Pentacles trudges through the cold, yet the light of sanctuary glows nearby.",
  },
  {
    id: "pentacles_06",
    name: "Six of Pentacles",
    suit: "pentacles",
    number: 6,
    imageUrl: "/manus-storage/minor_pentacles_06_8f92a2a7.png",
    uprightMeaning: "Giving, receiving, sharing wealth, generosity, charity",
    reversedMeaning: "Self-care, unpaid debts, one-sided charity",
    keywords: ["generosity", "charity", "giving", "receiving"],
    element: "Earth",
    description: "The Six of Pentacles distributes wealth with a balanced hand, embodying the flow of generosity.",
  },
  {
    id: "pentacles_07",
    name: "Seven of Pentacles",
    suit: "pentacles",
    number: 7,
    imageUrl: "/manus-storage/minor_pentacles_07_4d1db663.png",
    uprightMeaning: "Long-term view, sustainable results, perseverance, investment",
    reversedMeaning: "Lack of long-term vision, limited success or reward",
    keywords: ["patience", "investment", "long-term vision", "perseverance"],
    element: "Earth",
    description: "The Seven of Pentacles pauses to survey the harvest, contemplating the fruits of patient labor.",
  },
  {
    id: "pentacles_08",
    name: "Eight of Pentacles",
    suit: "pentacles",
    number: 8,
    imageUrl: "/manus-storage/minor_pentacles_08_c17dba3a.png",
    uprightMeaning: "Apprenticeship, repetitive tasks, mastery, skill development",
    reversedMeaning: "Self-development, perfectionism, misdirected activity",
    keywords: ["craftsmanship", "mastery", "diligence", "skill"],
    element: "Earth",
    description: "The Eight of Pentacles bends over the workbench, perfecting craft through dedicated, focused effort.",
  },
  {
    id: "pentacles_09",
    name: "Nine of Pentacles",
    suit: "pentacles",
    number: 9,
    imageUrl: "/manus-storage/minor_pentacles_09_be0de802.png",
    uprightMeaning: "Abundance, luxury, self-sufficiency, financial independence",
    reversedMeaning: "Self-worth, over-investment in work, hustling",
    keywords: ["abundance", "luxury", "self-sufficiency", "independence"],
    element: "Earth",
    description: "The Nine of Pentacles stands in a lush garden of self-made abundance, sovereign and serene.",
  },
  {
    id: "pentacles_10",
    name: "Ten of Pentacles",
    suit: "pentacles",
    number: 10,
    imageUrl: "/manus-storage/minor_pentacles_10_20a57b72.png",
    uprightMeaning: "Wealth, financial security, family, long-term success, contribution",
    reversedMeaning: "The dark side of wealth, financial failure or loss",
    keywords: ["legacy", "wealth", "family", "long-term success"],
    element: "Earth",
    description: "The Ten of Pentacles depicts a dynasty of abundance — legacy, family wealth, and enduring prosperity.",
  },
  {
    id: "pentacles_11_page",
    name: "Page of Pentacles",
    suit: "pentacles",
    number: 11,
    imageUrl: "/manus-storage/minor_pentacles_page_769a568c.png",
    uprightMeaning: "Manifestation, financial opportunity, skill development",
    reversedMeaning: "Lack of progress, procrastination, learn from failure",
    keywords: ["ambition", "diligence", "new opportunities", "study"],
    element: "Earth",
    description: "The Page of Pentacles holds a golden coin aloft, studying it with focused, earnest ambition.",
  },
  {
    id: "pentacles_12_knight",
    name: "Knight of Pentacles",
    suit: "pentacles",
    number: 12,
    imageUrl: "/manus-storage/minor_pentacles_knight_64a0208b.png",
    uprightMeaning: "Hard work, productivity, routine, conservatism",
    reversedMeaning: "Self-discipline, boredom, feeling stuck, perfectionism",
    keywords: ["reliability", "hard work", "patience", "thoroughness"],
    element: "Earth",
    description: "The Knight of Pentacles moves with steady, methodical purpose — reliable, patient, and thorough.",
  },
  {
    id: "pentacles_13_queen",
    name: "Queen of Pentacles",
    suit: "pentacles",
    number: 13,
    imageUrl: "/manus-storage/minor_pentacles_queen_f491a60a.png",
    uprightMeaning: "Practical, homely, motherly, down-to-earth, financially secure",
    reversedMeaning: "Financial independence, self-care, work-home conflict",
    keywords: ["nurturing", "practicality", "abundance", "security"],
    element: "Earth",
    description: "The Queen of Pentacles nurtures all in her domain with earthy wisdom and abundant generosity.",
  },
  {
    id: "pentacles_14_king",
    name: "King of Pentacles",
    suit: "pentacles",
    number: 14,
    imageUrl: "/manus-storage/minor_pentacles_king_0b416113.png",
    uprightMeaning: "Wealth, business, leadership, security, discipline, abundance",
    reversedMeaning: "Financially inept, obsessed with wealth and status, stubborn",
    keywords: ["wealth", "business", "leadership", "abundance"],
    element: "Earth",
    description: "The King of Pentacles sits upon a throne of earthly riches, master of material abundance and practical wisdom.",
  },
];

export const SPREAD_TYPES = {
  single: {
    id: "single",
    name: "Daily Draw",
    description: "A single card to guide your day",
    cardCount: 1,
    positions: ["Your Message for Today"],
  },
  three_card: {
    id: "three_card",
    name: "Past · Present · Future",
    description: "Three cards revealing the arc of your journey",
    cardCount: 3,
    positions: ["Past", "Present", "Future"],
  },
  celtic_cross: {
    id: "celtic_cross",
    name: "Celtic Cross",
    description: "A deep ten-card reading for comprehensive insight",
    cardCount: 10,
    positions: [
      "The Present",
      "The Challenge",
      "The Past",
      "The Future",
      "Above (Conscious)",
      "Below (Unconscious)",
      "Advice",
      "External Influences",
      "Hopes & Fears",
      "Outcome",
    ],
  },
  yes_no: {
    id: "yes_no",
    name: "Yes or No",
    description: "One card oracle for a direct answer",
    cardCount: 1,
    positions: ["The Oracle's Answer"],
  },
} as const;

export type SpreadType = keyof typeof SPREAD_TYPES;
